name: PR label automation

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Assigns labels automatically.
    runs-on: ubuntu-latest
    steps:
      - name: Performs verification by PR title and description.
        uses: hoho4190/issue-pr-labeler@9e93f7e2bbbdd60ce4b2946fb2bb8b172ac8b598
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          disable-bot: true
          config-file-name: labeler-by-title-and-body.yml
      - name: Performs verification by branch name.
        uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler-by-branch-name.yml
