name: Automatic assignment in pull request

on:
  pull_request:
    types: [ opened, ready_for_review ]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign:
    name: Assigns reviewers and authors
    runs-on: ubuntu-latest

    steps:
      - name: Execute
        uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e
        with:
          configuration-path: .github/auto-assign.yml
