name: Verification of composer.json

on:
  pull_request:
    paths:
      - composer.json

jobs:
  composer-check:
    name: Check normalization
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: PHP installation
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f
        with:
          php-version: 8.4

      - name: Dependency installation
        run: composer install --no-progress --no-interaction --ignore-platform-req=ext-ddtrace

      - name: Validate
        run: composer normalize --dry-run
