name: Code quality check

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  code-quality-check:
    if: github.event_name == 'pull_request' || github.event.pull_request == null
    name: Runs tests and SonarQube Scan.
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PHP installation
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f
        with:
          php-version: 8.4
          tools: composer
          coverage: xdebug

      - name: Dependency installation
        run: composer install --no-progress --no-interaction

      - name: Unit tests execution
        run: composer test-unit

      - name: Coverage tests execution
        run: composer test-coverage

      - name: Executa SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
