name: Changelog update

on:
  release:
    types: [ released ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    name: Update the CHANGELOG
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update the CHANGELOG.md file.
        uses: stefanzweifel/changelog-updater-action@a938690fad7edf25368f37e43a1ed1b34303eb36
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Performs commit of the CHANGELOG update.
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3
        with:
          branch: changelog-update
          create_branch: true
          file_pattern: CHANGELOG.md
          commit_message: 'docs: update CHANGELOG'
          commit_author: jnreginato <jnreginato@users.noreply.github.com>
